spring.application.name=urlshortener
server.port=${PORT:8081}
spring.data.mongodb.auto-index-creation=true

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/urlshortener}
app.base-url=${APP_BASE_URL:https://url-shortener-2-b4rf.onrender.com}
app.allowed-origins=${APP_ALLOWED_ORIGINS:http://localhost:5173}
#https://url-shortener-2-b4rf.onrender.com
