spring.application.name=urlshortener
server.port=8081
app.base-url=http://localhost:8081
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb+srv://prashanth:prashanth@test.k28t2.mongodb.net/urlshortener?appName=test
#mongodb+srv://prashanth:<db_password>@test.k28t2.mongodb.net/?appName=test
#mongodb+srv://prashanth:prashanth@test.k28t2.mongodb.net/urlshortener?appName=test
